<a href="https://colab.research.google.com/github/novoforce/Exploring-Pytorch/blob/master/new/1000_Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Video_Link](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=2)

In [2]:
import torch

# Initialising the tensors

In [3]:
#1
my_tensor= torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
#2
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
#3
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cuda')
print(my_tensor)

RuntimeError: ignored

In [ ]:
#4
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cpu') #cpu is the default
print(my_tensor)

In [ ]:
#5
#for calculating the gradients
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor)

In [ ]:
#6
#CUDA- Compute Unified Device Architecture   https://en.wikipedia.org/wiki/CUDA#:~:text=CUDA%20(Compute%20Unified%20Device%20Architecture,API)%20model%20created%20by%20Nvidia.
#the best way to add device(cpu/gpu) 
device= "cuda" if torch.cuda.is_available() else "cpu"
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device) #cpu is the default
print(my_tensor)

# Other initialization methods

In [ ]:
#7
x= torch.empty(size=(3,3)) #x will contain random values without any distribution
print(x)

In [ ]:
#8
x= torch.zeros((3,3)) #since 'size' is the first attribute so need to mention explicitly
print(x)

In [6]:
#9
#random values from uniform distribution from 0 to 1
x= torch.rand((3,3))
print(x)

tensor([[0.2044, 0.5136, 0.3987],
        [0.7786, 0.4671, 0.4056],
        [0.7043, 0.4289, 0.1391]])


In [7]:
#10
x= torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
#11
#This will create a Identity matrix
x= torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [9]:
#12
x= torch.arange(start=0,end=5,step=1) #same like range() in python
print(x)

tensor([0, 1, 2, 3, 4])


In [10]:
#13
x= torch.linspace(start=0.1,end=1,steps=10) #start at 0.1 and end at 1 and will have exactly 10 values
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [11]:
#14
x= torch.empty((1,5)).normal_(mean=0,std=1) #empty values will be normally distributed
print(x)
print("==============================================================")
x= torch.empty((1,5))
print('unitialized tensor---->',x)
x.normal_(mean=0,std=1)
print('unitialized tensor after normalizing---->',x)

tensor([[-0.7341, -0.9014, -0.2405,  0.7147,  0.4019]])
unitialized tensor----> tensor([[3.5116e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00,        nan]])
unitialized tensor after normalizing----> tensor([[ 2.1914,  0.7113, -0.7494,  0.9997, -1.2037]])


In [12]:
#15
x= torch.empty((1,5)).uniform_(0,1) #here 0,1 is the lower and the upper range
print(x)

tensor([[0.9729, 0.4495, 0.4316, 0.4863, 0.5210]])


In [13]:
#16
x= torch.diag(torch.ones(3)) #3x3 diagona matrix 
print(x)

#similar to code snippet #11
#Note: torch.diag is used to preserve the diagonal values whereas the torch.eye() is used for diagonal= 1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# Attributes of tensors

In [14]:
#7
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad) #this will be true if the my_tensor has gradient

torch.float32
cpu
torch.Size([2, 3])
True


# How to initialize and convert tensors to other types(int,float,double)

In [15]:
#17
tensor= torch.arange(4)
print(tensor,'datatype->',tensor.dtype)
print(tensor.bool(),'datatype->',tensor.bool().dtype)
print(tensor.short(),'datatype->',tensor.short().dtype)
print(tensor.long(),'datatype->',tensor.long().dtype)# IMPORTANT
print(tensor.half(),'datatype->',tensor.half().dtype)
print(tensor.float(),'datatype->',tensor.float().dtype)# IMPORTANT

tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([False,  True,  True,  True]) datatype-> torch.bool
tensor([0, 1, 2, 3], dtype=torch.int16) datatype-> torch.int16
tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16) datatype-> torch.float16
tensor([0., 1., 2., 3.]) datatype-> torch.float32


# Array to Tensor conversion and vice-versa

In [16]:
#18
import numpy as np

In [17]:
#19
np_array= np.zeros((5,5))
print('np_array:',np_array)
tensor= torch.from_numpy(np_array)
print('tensor:',tensor)
np_array_back= tensor.numpy()
print('np_array_back:',np_array_back)

np_array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
np_array_back: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math & Comparison Operations

In [18]:
#20
x= torch.tensor([1,2,3])
y= torch.tensor([9,8,7])

In [19]:
#21
#Addition operations
z1= torch.empty(3)
torch.add(x,y,out=z1) #first way
print('Addition: ',z1)
print("============================")
z2= torch.add(x,y) #second way
print('Addition: ',z2)
print("============================")
z3= x+y #third way
print('Addition: ',z3)

print("============================")
#Subtraction operation
z= x-y
print('Subtarction: ',z)

print("============================")
#Mulitiplication
z= x*y
print("Mulitiplication",z)

Addition:  tensor([10., 10., 10.])
Addition:  tensor([10, 10, 10])
Addition:  tensor([10, 10, 10])
Subtarction:  tensor([-8, -6, -4])
Mulitiplication tensor([ 9, 16, 21])


In [20]:
#22
#Division operation
z= torch.true_divide(x,y) #will do element wise division and return the values in the form of tensor
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2])
z= torch.true_divide(x,y) # this will divide x/y elementwise
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2,3])
z= torch.true_divide(x,y) #This will throw error as len(x) !=len(y)
print('Division: ',z)

Division:  tensor([0.1111, 0.2500, 0.4286])
Division:  tensor([0.5000, 1.0000, 1.5000])


RuntimeError: ignored

In [ ]:
#23
#Exponential Operation
x= torch.tensor([10,20,30])
z= x.pow(2)
print(z)
z= x**2
print(z)

In [21]:
#24
#Simple Comparison
z= x>0
print(z)

tensor([True, True, True])


In [22]:
#25
#Matrix multiplication
x1= torch.rand((2,5))
x2= torch.rand((5,3))
x3= torch.mm(x1,x2)  #Output shape= (2x3)
print('Matrix multiplication: ',x3)
x3= x1.mm(x2)  #Output shape= (2x3)
print('Matrix multiplication: ',x3)

Matrix multiplication:  tensor([[1.7016, 0.7160, 0.5608],
        [2.0721, 1.2453, 1.8302]])
Matrix multiplication:  tensor([[1.7016, 0.7160, 0.5608],
        [2.0721, 1.2453, 1.8302]])


In [23]:
#26
#Matrix Exponentiation
matrix_exp= torch.rand(5,5)
print('Matrix: ',matrix_exp)
print('Power of Matrix: ',matrix_exp.matrix_power(3))
print('Another way Power of Matrix: ',torch.matrix_power(matrix_exp, 3)) #Another way

Matrix:  tensor([[0.3361, 0.9619, 0.1880, 0.2480, 0.7574],
        [0.8257, 0.7907, 0.0389, 0.1683, 0.6875],
        [0.2604, 0.1706, 0.3207, 0.9916, 0.1082],
        [0.7817, 0.6284, 0.9026, 0.6676, 0.8654],
        [0.9465, 0.6709, 0.7879, 0.9855, 0.1990]])
Power of Matrix:  tensor([[4.6345, 5.0881, 2.9729, 3.9150, 4.1654],
        [4.7460, 5.0946, 2.8868, 3.8599, 4.0703],
        [3.7192, 3.8022, 2.6660, 3.6137, 3.0703],
        [6.9511, 7.2882, 4.8213, 6.2285, 6.1564],
        [6.5880, 6.7480, 4.4434, 5.8350, 5.4499]])
Another way Power of Matrix:  tensor([[4.6345, 5.0881, 2.9729, 3.9150, 4.1654],
        [4.7460, 5.0946, 2.8868, 3.8599, 4.0703],
        [3.7192, 3.8022, 2.6660, 3.6137, 3.0703],
        [6.9511, 7.2882, 4.8213, 6.2285, 6.1564],
        [6.5880, 6.7480, 4.4434, 5.8350, 5.4499]])


In [24]:
#27
# Difference between Matrix multiplication and Elementwise multiplication
x= torch.tensor([1,2,3]) #(r0,c0)
y= torch.tensor([9,8,7]) #(r1,c1)

element_wise_mul= x*y
print("Elementwise multiplication:",element_wise_mul)
#matrix_mul= torch.mm(x,y)  #This will throw error as len(c0) != len(r1) 
#print("Matrix_multiplication:",matrix_mul)

Elementwise multiplication: tensor([ 9, 16, 21])


In [25]:
#28
#Dot Product of Matrices (will only work on 1D tensors)
#Dot product= elementwise matrix multiplication + Adding/Summing the result
z= torch.dot(x,y)   #tensor([ 9, 16, 21]) ==> 9+16+21 = 46
print('Dot Product: ',z)

Dot Product:  tensor(46)


In [26]:
#29
# x= torch.tensor([1,2,3,4,5,6]).reshape(3,2)
# y= torch.tensor([2,2,2,2,2,2]).reshape(2,3)
# z= torch.dot(x,y)
# print(z)

#Batch Multiplication
batch= 32
n= 10
m= 10
p= 30

tensor1= torch.rand((batch,n,m))
tensor2= torch.rand((batch,m,p))
out_bmm= torch.bmm(tensor1,tensor2) #shape= (batch,n,p) => (32,10,30)
print(out_bmm,'shape:> ',out_bmm.shape)

tensor([[[3.3142, 2.6600, 4.2329,  ..., 2.9608, 5.1776, 3.6568],
         [2.4583, 1.8511, 2.4627,  ..., 1.7147, 3.0940, 2.7337],
         [2.9687, 2.2704, 2.6273,  ..., 1.9871, 3.8016, 3.5053],
         ...,
         [1.9756, 1.2809, 2.1154,  ..., 1.7381, 2.9641, 1.9098],
         [3.9793, 2.6685, 3.9114,  ..., 3.0103, 4.6835, 3.6147],
         [3.0413, 2.2498, 3.1165,  ..., 2.3860, 3.9460, 2.7906]],

        [[2.4466, 2.7960, 2.8469,  ..., 3.0303, 2.2577, 1.8552],
         [3.1358, 3.0486, 4.0652,  ..., 4.3268, 2.9829, 2.8181],
         [2.2344, 2.0720, 3.2575,  ..., 3.2407, 2.2047, 2.1073],
         ...,
         [2.9076, 2.8964, 3.6935,  ..., 3.7622, 2.5392, 2.4523],
         [3.0432, 2.2368, 3.6783,  ..., 3.3505, 2.9480, 2.4920],
         [3.4837, 3.0330, 3.4174,  ..., 4.1035, 3.4829, 2.9930]],

        [[3.5919, 2.4990, 2.8122,  ..., 2.3141, 2.6986, 2.7544],
         [2.9867, 2.1003, 2.5828,  ..., 2.2060, 2.1179, 2.2019],
         [3.6975, 2.5083, 3.4179,  ..., 3.0218, 3.1905, 3.

# Broadcasting

In [27]:
#30
x1= torch.rand((5,5))  #(5x5)
x2= torch.rand((1,5))  #(1x5)
print('x1: ',x1)
print('x2: ',x2)
z= x1-x2 #Mathematically this is wrong operation
print(z)
z= x1**x2 #Mathematically this is wrong operation
print(z)

x1:  tensor([[0.0623, 0.3950, 0.0623, 0.4409, 0.1484],
        [0.1747, 0.4108, 0.4635, 0.2949, 0.9325],
        [0.6038, 0.3797, 0.2519, 0.1746, 0.8110],
        [0.1388, 0.6738, 0.8548, 0.5304, 0.9737],
        [0.3452, 0.6002, 0.8078, 0.7697, 0.4684]])
x2:  tensor([[0.4427, 0.8490, 0.3700, 0.8448, 0.9901]])
tensor([[-0.3804, -0.4540, -0.3076, -0.4039, -0.8417],
        [-0.2679, -0.4381,  0.0936, -0.5499, -0.0576],
        [ 0.1611, -0.4692, -0.1180, -0.6702, -0.1790],
        [-0.3039, -0.1752,  0.4848, -0.3144, -0.0164],
        [-0.0975, -0.2487,  0.4378, -0.0751, -0.5217]])
tensor([[0.2926, 0.4544, 0.3582, 0.5007, 0.1512],
        [0.4620, 0.4699, 0.7524, 0.3564, 0.9331],
        [0.7999, 0.4395, 0.6005, 0.2289, 0.8127],
        [0.4172, 0.7152, 0.9436, 0.5852, 0.9739],
        [0.6245, 0.6483, 0.9241, 0.8016, 0.4719]])


# Other useful tensor operations

In [28]:
#31
#Summation with dim attribute
x= torch.tensor([[1,1,1],[4,5,6],[7,8,9]])
print('x: ',x)
sum_x= torch.sum(x,dim=0)
sum_y= torch.sum(x,dim=1)
print(sum_x,sum_y)

#Min and Max
values,indices= torch.max(x,dim=0) #return max row
print('max: ',values,indices)

values,indices= torch.max(x,dim=1) #return max col
print('max: ',values,indices)

values,indices= torch.min(x,dim=0) #return min row
print('min: ',values,indices)

values,indices= torch.min(x,dim=1) #return min col
print('min: ',values,indices)

#absolute value
abs_x= torch.abs(x)
print('absolute value: ',abs_x)

#argmax function
z= torch.argmax(x,dim=0)# same as torch.max() but this will return only the location.
print('argmax: ',z)

z= torch.argmin(x,dim=0)# same as torch.max() but this will return only the location.
print('argmin: ',z)

#mean value
mean_x= torch.mean(x.float(),dim=0) #for calculating the mean the input tensor should be of FLOAT type 
print('Mean: ',mean_x)

x:  tensor([[1, 1, 1],
        [4, 5, 6],
        [7, 8, 9]])
tensor([12, 14, 16]) tensor([ 3, 15, 24])
max:  tensor([7, 8, 9]) tensor([2, 2, 2])
max:  tensor([1, 6, 9]) tensor([0, 2, 2])
min:  tensor([1, 1, 1]) tensor([0, 0, 0])
min:  tensor([1, 4, 7]) tensor([0, 0, 0])
absolute value:  tensor([[1, 1, 1],
        [4, 5, 6],
        [7, 8, 9]])
argmax:  tensor([2, 2, 2])
argmin:  tensor([0, 0, 0])
Mean:  tensor([4.0000, 4.6667, 5.3333])


In [29]:
#32
x= torch.tensor([1,2,3]) #(r0,c0)
y= torch.tensor([9,8,7]) #(r1,c1)
z= torch.eq(x,y)
print("Is the 2 tensors equal? ",z)

sorted_y, indices= torch.sort(y,dim=0,descending=False)
print(sorted_y,indices)

z= torch.clamp(x,min=0) #less than 0 will be 0
print("clamped tensor: ",z)

z= torch.clamp(x,min=0,max=2)
print("clamped tensor: ",z)

#Relu is a special function of clamp

Is the 2 tensors equal?  tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
clamped tensor:  tensor([1, 2, 3])
clamped tensor:  tensor([1, 2, 2])


In [30]:
#33
x= torch.tensor([1,0,1,1,1],dtype=torch.bool)
print('x: ',x)
z= torch.any(x) #OR function
print('any: ',z)

z= torch.all(x) #AND function
print('all: ',z)

x= torch.arange(10)
print('x: ',x)
print('Filtering operation: ',torch.where(x>5,x,x**2)) #----IMPORTANT (if x>5 then x otherwise x^2)
print('Unique values: ',torch.tensor([0,0,1,2,2,3,4]).unique())
print('No of dimensions: ',x.ndimension())
print('No of elements in x: ',x.numel()) #similar to len(x) but bit different in case of nD tensor

#difference between numel() and len()--> len() is basically calculates width/row
x1= torch.rand([3,5])
print('No of elements in x1: ',x1.numel(),len(x1))

x:  tensor([ True, False,  True,  True,  True])
any:  tensor(True)
all:  tensor(False)
x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Filtering operation:  tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])
Unique values:  tensor([0, 1, 2, 3, 4])
No of dimensions:  1
No of elements in x:  10
No of elements in x1:  15 3


# Indexing

In [31]:
#34
# Tensor Indexing
batch_size= 10
features= 25
x= torch.rand((batch_size,features))
print('x: ',x,'shape: ',x.shape,'dtype: ',x.dtype)

print("=====================================================================================================")
print('Features of first example: ')
print('first row and all column in first row: ',x[0],'shape: ',x[0].shape)

print("=====================================================================================================")
print('First feature for all the examples: ')
print(x[:,0],'shape: ',x[:,0].shape)

print("=====================================================================================================")
print('First 10 features of 2nd batch: ')
print(x[2,0:10],'shape: ',x[2,0:10].shape)


x:  tensor([[0.5942, 0.9293, 0.2717, 0.1990, 0.6920, 0.5712, 0.3536, 0.4504, 0.0762,
         0.4046, 0.6038, 0.1898, 0.7541, 0.3277, 0.4907, 0.3754, 0.3133, 0.1621,
         0.4054, 0.1928, 0.7535, 0.2280, 0.1345, 0.3413, 0.4178],
        [0.9485, 0.3945, 0.7979, 0.6279, 0.2778, 0.1094, 0.5883, 0.2282, 0.5924,
         0.9150, 0.4225, 0.7656, 0.6060, 0.1549, 0.0262, 0.8201, 0.4855, 0.8416,
         0.7339, 0.9636, 0.6752, 0.2090, 0.3492, 0.0294, 0.9538],
        [0.0212, 0.6040, 0.6956, 0.0121, 0.2529, 0.5721, 0.6692, 0.3025, 0.9975,
         0.8599, 0.5745, 0.9534, 0.9412, 0.9637, 0.6457, 0.3683, 0.2590, 0.3732,
         0.8888, 0.8079, 0.2745, 0.8938, 0.9107, 0.4585, 0.9697],
        [0.2188, 0.3779, 0.8072, 0.9806, 0.7966, 0.3255, 0.2833, 0.0748, 0.6469,
         0.4084, 0.9999, 0.8767, 0.4455, 0.7025, 0.8899, 0.2122, 0.2872, 0.1421,
         0.1489, 0.5795, 0.1007, 0.0951, 0.3073, 0.3810, 0.3693],
        [0.8339, 0.9230, 0.6229, 0.0499, 0.0098, 0.5257, 0.0256, 0.6024, 0.9532,
   

In [32]:
#35
#Fancy Indexing
x= torch.arange(10)
print('x: ',x)
idices= [2,5,8]
print('indexed values: ',x[indices])

print("=====================================")

x= torch.rand((3,5))
print('x: ',x)
rows= torch.tensor([1,0])
cols= torch.tensor([4,0])
print('Indexed value: ',x[rows,cols])

print("=====================================")

x= torch.arange(10)
print('x: ',x)
print('indexed value: ',x[(x<2) | (x>8)])
print('indexed value: ',x[(x>2) & (x<8)])
print('indexed values: ',x[x.remainder(2)==0]) #elementwise x%2==0 will be filtered  -----Important


x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
indexed values:  tensor([2, 1, 0])
x:  tensor([[0.3586, 0.2355, 0.5920, 0.5192, 0.9798],
        [0.4996, 0.4068, 0.0211, 0.6178, 0.2309],
        [0.1081, 0.0067, 0.4958, 0.3360, 0.0843]])
Indexed value:  tensor([0.2309, 0.3586])
x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
indexed value:  tensor([0, 1, 9])
indexed value:  tensor([3, 4, 5, 6, 7])
indexed values:  tensor([0, 2, 4, 6, 8])


# Tensor Reshaping

[Difference between reshape and view](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

In [33]:
#36
x= torch.arange(9)
x_3x3= x.view(3,3)
x_reshaped= x.reshape(3,3)
print('x: ',x)
print('x_3x3: ',x_3x3)
print('x_reshaped: ',x_reshaped)

print("====================================Experiment=======================================")
a= torch.arange(9)
print('a: ',a)
print("-------------------->")
b= a.view(3,3)
print('b: ',b)
print("-------------------->")
c= b.t()
print('c: ',c)
print("-------------------->")
# d= c.view(9) # This will throw error
d= c.contiguous().view(9)
print('d: ',d)
print("====================>")
x= a.reshape(3,3)
print('x: ',x)
print("-------------------->")
y= x.t()
print('y:',y)
print("-------------------->")
z= y.reshape(9)
print('z: ',z)

x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
x_3x3:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
x_reshaped:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
====================================Experiment=======================================
a:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
-------------------->
b:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
-------------------->
c:  tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
-------------------->
d:  tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
====================>
x:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
-------------------->
y: tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
-------------------->
z:  tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [37]:
#37
x1= torch.rand((2,5)) #(2,5)
x2= torch.rand((2,5)) #(2,5)
print('x1: ',x1)
print('x2: ',x2)
x3= torch.cat((x1,x2),dim=0) #across rows (4,5)
print('After concatination: ',x3)

x3= torch.cat((x1,x2),dim=1) #across rows (2,10)
print('After concatination: ',x3)

#Unroll the tensor
x1_unrolled= x1.view(-1)
print('unrolled: ',x1_unrolled) #compare x1 and x_unrolled

#fancy unrolling
batch= 64
x= torch.rand((batch,2,5))
z= x.view(batch,-1)
print('z shape: ',z.shape)

x1:  tensor([[0.5671, 0.5407, 0.5156, 0.7262, 0.9496],
        [0.2194, 0.4327, 0.3335, 0.0704, 0.4878]])
x2:  tensor([[0.1037, 0.7123, 0.1746, 0.0313, 0.2229],
        [0.2926, 0.8010, 0.2982, 0.5280, 0.2099]])
After concatination:  tensor([[0.5671, 0.5407, 0.5156, 0.7262, 0.9496],
        [0.2194, 0.4327, 0.3335, 0.0704, 0.4878],
        [0.1037, 0.7123, 0.1746, 0.0313, 0.2229],
        [0.2926, 0.8010, 0.2982, 0.5280, 0.2099]])
After concatination:  tensor([[0.5671, 0.5407, 0.5156, 0.7262, 0.9496, 0.1037, 0.7123, 0.1746, 0.0313,
         0.2229],
        [0.2194, 0.4327, 0.3335, 0.0704, 0.4878, 0.2926, 0.8010, 0.2982, 0.5280,
         0.2099]])
unrolled:  tensor([0.5671, 0.5407, 0.5156, 0.7262, 0.9496, 0.2194, 0.4327, 0.3335, 0.0704,
        0.4878])
z shape:  torch.Size([64, 10])


In [46]:
#38
#Transposing across multiple dimenions ----> use permute.. special case of transpose 't()'
batch= 64
x= torch.rand((batch,2,5)) # tensor of 64x2x5
print('initial shape: ',x.shape)
x= x.permute(0,2,1)
print('final shape: ',x.shape)

#Adding dimensions
x= torch.arange(10) #shape is[10]
print('x: ',x,'x.shape: ',x.shape)
print("-------------------------------------------")
y= x.unsqueeze(0)
print('y: ',y,'y.shape: ',y.shape)
print("-------------------------------------------")
z= x.unsqueeze(1)
print('z: ',z,'z.shape: ',z.shape)

print("============================================")
x= torch.arange(10).unsqueeze(0).unsqueeze(1)
print('x: ',x,'x.shape: ',x.shape)
print("============================================")
x= torch.arange(10).unsqueeze(1).unsqueeze(0)
print('x: ',x,'x.shape: ',x.shape)
print("============================================")
x= torch.arange(10).unsqueeze(0).unsqueeze(1)
z= x.squeeze(1)
print('z: ',z,'z.shape: ',z.shape)



initial shape:  torch.Size([64, 2, 5])
final shape:  torch.Size([64, 5, 2])
x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) x.shape:  torch.Size([10])
-------------------------------------------
y:  tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) y.shape:  torch.Size([1, 10])
-------------------------------------------
z:  tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) z.shape:  torch.Size([10, 1])
x:  tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]) x.shape:  torch.Size([1, 1, 10])
x:  tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]]) x.shape:  torch.Size([1, 10, 1])
z:  tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) z.shape:  torch.Size([1, 10])
