<a href="https://colab.research.google.com/github/novoforce/Exploring-Pytorch/blob/master/new/1000_Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Video_Link](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=2)

In [ ]:
import torch

# Initialising the tensors

In [110]:
#1
my_tensor= torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
#2
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
#3
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cuda')
print(my_tensor)

RuntimeError: ignored

In [ ]:
#4
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cpu') #cpu is the default
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
#5
#for calculating the gradients
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [ ]:
#6
#CUDA- Compute Unified Device Architecture   https://en.wikipedia.org/wiki/CUDA#:~:text=CUDA%20(Compute%20Unified%20Device%20Architecture,API)%20model%20created%20by%20Nvidia.
#the best way to add device(cpu/gpu) 
device= "cuda" if torch.cuda.is_available() else "cpu"
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device) #cpu is the default
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Other initialization methods

In [ ]:
#7
x= torch.empty(size=(3,3)) #x will contain random values without any distribution
print(x)

tensor([[8.4170e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 2.0022e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [ ]:
#8
x= torch.zeros((3,3)) #since 'size' is the first attribute so need to mention explicitly
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#9
#random values from uniform distribution from 0 to 1
x= torch.rand((3,3))
print(x)

tensor([[0.9773, 0.0419, 0.7695],
        [0.3718, 0.8906, 0.9822],
        [0.7897, 0.7696, 0.2020]])


In [ ]:
#10
x= torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#11
#This will create a Identity matrix
x= torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
#12
x= torch.arange(start=0,end=5,step=1) #same like range() in python
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
#13
x= torch.linspace(start=0.1,end=1,steps=10) #start at 0.1 and end at 1 and will have exactly 10 values
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [ ]:
#14
x= torch.empty((1,5)).normal_(mean=0,std=1) #empty values will be normally distributed
print(x)
print("==============================================================")
x= torch.empty((1,5))
print('unitialized tensor---->',x)
x.normal_(mean=0,std=1)
print('unitialized tensor after normalizing---->',x)

tensor([[-0.2007,  0.3872, -0.8723,  0.9609,  0.5665]])
unitialized tensor----> tensor([[8.4185e-36, 0.0000e+00, 6.1743e+16, 1.4584e-19, 3.1432e-12]])
unitialized tensor after normalizing----> tensor([[ 1.0151,  0.7705, -0.4465, -1.1419,  0.3085]])


In [ ]:
#15
x= torch.empty((1,5)).uniform_(0,1) #here 0,1 is the lower and the upper range
print(x)

tensor([[0.3746, 0.9362, 0.3018, 0.8543, 0.8325]])


In [ ]:
#16
x= torch.diag(torch.ones(3)) #3x3 diagona matrix 
print(x)

#similar to code snippet #11
#Note: torch.diag is used to preserve the diagonal values whereas the torch.eye() is used for diagonal= 1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# Attributes of tensors

In [ ]:
#7
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad) #this will be true if the my_tensor has gradient

torch.float32
cpu
torch.Size([2, 3])
True


# How to initialize and convert tensors to other types(int,float,double)

In [ ]:
#17
tensor= torch.arange(4)
print(tensor,'datatype->',tensor.dtype)
print(tensor.bool(),'datatype->',tensor.bool().dtype)
print(tensor.short(),'datatype->',tensor.short().dtype)
print(tensor.long(),'datatype->',tensor.long().dtype)# IMPORTANT
print(tensor.half(),'datatype->',tensor.half().dtype)
print(tensor.float(),'datatype->',tensor.float().dtype)# IMPORTANT

tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([False,  True,  True,  True]) datatype-> torch.bool
tensor([0, 1, 2, 3], dtype=torch.int16) datatype-> torch.int16
tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16) datatype-> torch.float16
tensor([0., 1., 2., 3.]) datatype-> torch.float32


# Array to Tensor conversion and vice-versa

In [ ]:
#18
import numpy as np

In [ ]:
#19
np_array= np.zeros((5,5))
print('np_array:',np_array)
tensor= torch.from_numpy(np_array)
print('tensor:',tensor)
np_array_back= tensor.numpy()
print('np_array_back:',np_array_back)

np_array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
np_array_back: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math & Comparison Operations

In [ ]:
#20
x= torch.tensor([1,2,3])
y= torch.tensor([9,8,7])

In [ ]:
#21
#Addition operations
z1= torch.empty(3)
torch.add(x,y,out=z1) #first way
print('Addition: ',z1)
print("============================")
z2= torch.add(x,y) #second way
print('Addition: ',z2)
print("============================")
z3= x+y #third way
print('Addition: ',z3)

print("============================")
#Subtraction operation
z= x-y
print('Subtarction: ',z)

print("============================")
#Mulitiplication
z= x*y
print("Mulitiplication",z)

Addition:  tensor([10., 10., 10.])
Addition:  tensor([10, 10, 10])
Addition:  tensor([10, 10, 10])
Subtarction:  tensor([-8, -6, -4])
Mulitiplication tensor([ 9, 16, 21])


In [ ]:
#22
#Division operation
z= torch.true_divide(x,y) #will do element wise division and return the values in the form of tensor
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2])
z= torch.true_divide(x,y) # this will divide x/y elementwise
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2,3])
z= torch.true_divide(x,y) #This will throw error as len(x) !=len(y)
print('Division: ',z)

Division:  tensor([0.1111, 0.2500, 0.4286])
Division:  tensor([0.5000, 1.0000, 1.5000])


RuntimeError: ignored

In [ ]:
#23
#Exponential Operation
x= torch.tensor([10,20,30])
z= x.pow(2)
print(z)
z= x**2
print(z)

tensor([100, 400, 900])
tensor([100, 400, 900])


In [ ]:
#24
#Simple Comparison
z= x>0
print(z)

tensor([True, True, True])


In [ ]:
#25
#Matrix multiplication
x1= torch.rand((2,5))
x2= torch.rand((5,3))
x3= torch.mm(x1,x2)  #Output shape= (2x3)
print('Matrix multiplication: ',x3)
x3= x1.mm(x2)  #Output shape= (2x3)
print('Matrix multiplication: ',x3)

Matrix multiplication:  tensor([[1.2715, 1.1609, 0.6173],
        [1.9431, 1.7158, 1.0504]])
Matrix multiplication:  tensor([[1.2715, 1.1609, 0.6173],
        [1.9431, 1.7158, 1.0504]])


In [ ]:
#26
#Matrix Exponentiation
matrix_exp= torch.rand(5,5)
print('Matrix: ',matrix_exp)
print('Power of Matrix: ',matrix_exp.matrix_power(3))
print('Another way Power of Matrix: ',torch.matrix_power(matrix_exp, 3)) #Another way

Matrix:  tensor([[0.4736, 0.0513, 0.0884, 0.0803, 0.8073],
        [0.2221, 0.1744, 0.2359, 0.7896, 0.2892],
        [0.2141, 0.3215, 0.5776, 0.3423, 0.9920],
        [0.3688, 0.1808, 0.6775, 0.8923, 0.8104],
        [0.8614, 0.5578, 0.6677, 0.1083, 0.2233]])
Power of Matrix:  tensor([[1.4584, 0.8224, 1.2833, 1.0516, 2.0163],
        [2.0048, 1.2362, 2.1376, 1.7028, 2.6817],
        [2.5585, 1.5478, 2.5722, 2.1723, 3.6076],
        [3.3325, 2.0507, 3.4209, 2.7176, 4.4485],
        [2.4597, 1.4757, 2.3579, 1.6932, 2.7528]])
Another way Power of Matrix:  tensor([[1.4584, 0.8224, 1.2833, 1.0516, 2.0163],
        [2.0048, 1.2362, 2.1376, 1.7028, 2.6817],
        [2.5585, 1.5478, 2.5722, 2.1723, 3.6076],
        [3.3325, 2.0507, 3.4209, 2.7176, 4.4485],
        [2.4597, 1.4757, 2.3579, 1.6932, 2.7528]])


In [ ]:
#27
# Difference between Matrix multiplication and Elementwise multiplication
x= torch.tensor([1,2,3]) #(r0,c0)
y= torch.tensor([9,8,7]) #(r1,c1)

element_wise_mul= x*y
print("Elementwise multiplication:",element_wise_mul)
#matrix_mul= torch.mm(x,y)  #This will throw error as len(c0) != len(r1) 
#print("Matrix_multiplication:",matrix_mul)

Elementwise multiplication: tensor([ 9, 16, 21])


In [ ]:
#28
#Dot Product of Matrices (will only work on 1D tensors)
#Dot product= elementwise matrix multiplication + Adding/Summing the result
z= torch.dot(x,y)   #tensor([ 9, 16, 21]) ==> 9+16+21 = 46
print('Dot Product: ',z)

Dot Product:  tensor(46)


In [ ]:
#29
# x= torch.tensor([1,2,3,4,5,6]).reshape(3,2)
# y= torch.tensor([2,2,2,2,2,2]).reshape(2,3)
# z= torch.dot(x,y)
# print(z)

#Batch Multiplication
batch= 32
n= 10
m= 10
p= 30

tensor1= torch.rand((batch,n,m))
tensor2= torch.rand((batch,m,p))
out_bmm= torch.bmm(tensor1,tensor2) #shape= (batch,n,p) => (32,10,30)
print(out_bmm,'shape:> ',out_bmm.shape)

tensor([[[0.6746, 1.3440, 1.5197,  ..., 1.4123, 1.3092, 1.1815],
         [1.9681, 2.1597, 2.5410,  ..., 2.4502, 2.6391, 1.4104],
         [1.6546, 2.1081, 2.3160,  ..., 2.6406, 2.2823, 1.5866],
         ...,
         [1.6251, 1.8965, 2.2700,  ..., 2.1964, 2.2914, 0.9966],
         [1.8708, 2.2831, 2.3218,  ..., 2.7869, 2.7840, 1.8509],
         [1.8790, 1.9613, 2.3707,  ..., 2.4906, 2.5309, 1.7560]],

        [[2.5538, 1.8276, 2.0366,  ..., 2.7297, 2.5293, 2.2667],
         [2.0807, 2.5479, 1.4353,  ..., 2.3295, 1.8959, 1.9945],
         [3.6322, 2.7574, 2.6385,  ..., 3.6439, 3.7565, 2.6429],
         ...,
         [2.7594, 2.4373, 1.7515,  ..., 3.4817, 2.8378, 2.7829],
         [2.2292, 1.5217, 1.4299,  ..., 2.4790, 2.6641, 1.9960],
         [2.8451, 2.1684, 2.3297,  ..., 3.2520, 3.5597, 2.9761]],

        [[2.0431, 1.7959, 1.3607,  ..., 1.4927, 2.2477, 1.9066],
         [1.7901, 1.5013, 1.5527,  ..., 1.4306, 2.2598, 1.9273],
         [2.1534, 2.4207, 2.0770,  ..., 1.9229, 2.0720, 2.

# Broadcasting

In [ ]:
#30
x1= torch.rand((5,5))  #(5x5)
x2= torch.rand((1,5))  #(1x5)
print('x1: ',x1)
print('x2: ',x2)
z= x1-x2 #Mathematically this is wrong operation
print(z)
z= x1**x2 #Mathematically this is wrong operation
print(z)

x1:  tensor([[0.2572, 0.6125, 0.8028, 0.5707, 0.6523],
        [0.6456, 0.8701, 0.3016, 0.1734, 0.5940],
        [0.4459, 0.7461, 0.6255, 0.1587, 0.7322],
        [0.2246, 0.6975, 0.3298, 0.9043, 0.6916],
        [0.7365, 0.3020, 0.6561, 0.2501, 0.3893]])
x2:  tensor([[0.4265, 0.0819, 0.4527, 0.0407, 0.5531]])
tensor([[-0.1693,  0.5306,  0.3501,  0.5300,  0.0992],
        [ 0.2191,  0.7882, -0.1511,  0.1327,  0.0409],
        [ 0.0194,  0.6642,  0.1728,  0.1180,  0.1790],
        [-0.2019,  0.6157, -0.1229,  0.8636,  0.1385],
        [ 0.3100,  0.2201,  0.2034,  0.2094, -0.1638]])
tensor([[0.5604, 0.9607, 0.9054, 0.9774, 0.7895],
        [0.8298, 0.9887, 0.5812, 0.9312, 0.7497],
        [0.7086, 0.9763, 0.8086, 0.9278, 0.8416],
        [0.5289, 0.9709, 0.6052, 0.9959, 0.8155],
        [0.8777, 0.9066, 0.8263, 0.9451, 0.5935]])


# Other useful tensor operations

In [ ]:
#31
#Summation with dim attribute
x= torch.tensor([[1,1,1],[4,5,6],[7,8,9]])
print('x: ',x)
sum_x= torch.sum(x,dim=0)
sum_y= torch.sum(x,dim=1)
print(sum_x,sum_y)

#Min and Max
values,indices= torch.max(x,dim=0) #return max row
print('max: ',values,indices)

values,indices= torch.max(x,dim=1) #return max col
print('max: ',values,indices)

values,indices= torch.min(x,dim=0) #return min row
print('min: ',values,indices)

values,indices= torch.min(x,dim=1) #return min col
print('min: ',values,indices)

#absolute value
abs_x= torch.abs(x)
print('absolute value: ',abs_x)

#argmax function
z= torch.argmax(x,dim=0)# same as torch.max() but this will return only the location.
print('argmax: ',z)

z= torch.argmin(x,dim=0)# same as torch.max() but this will return only the location.
print('argmin: ',z)

#mean value
mean_x= torch.mean(x.float(),dim=0) #for calculating the mean the input tensor should be of FLOAT type 
print('Mean: ',mean_x)

x:  tensor([[1, 1, 1],
        [4, 5, 6],
        [7, 8, 9]])
tensor([12, 14, 16]) tensor([ 3, 15, 24])
max:  tensor([7, 8, 9]) tensor([2, 2, 2])
max:  tensor([1, 6, 9]) tensor([0, 2, 2])
min:  tensor([1, 1, 1]) tensor([0, 0, 0])
min:  tensor([1, 4, 7]) tensor([0, 0, 0])
absolute value:  tensor([[1, 1, 1],
        [4, 5, 6],
        [7, 8, 9]])
argmax:  tensor([2, 2, 2])
argmin:  tensor([0, 0, 0])
Mean:  tensor([4.0000, 4.6667, 5.3333])


In [ ]:
#32
x= torch.tensor([1,2,3]) #(r0,c0)
y= torch.tensor([9,8,7]) #(r1,c1)
z= torch.eq(x,y)
print("Is the 2 tensors equal? ",z)

sorted_y, indices= torch.sort(y,dim=0,descending=False)
print(sorted_y,indices)

z= torch.clamp(x,min=0) #less than 0 will be 0
print("clamped tensor: ",z)

z= torch.clamp(x,min=0,max=2)
print("clamped tensor: ",z)

#Relu is a special function of clamp

Is the 2 tensors equal?  tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
clamped tensor:  tensor([1, 2, 3])
clamped tensor:  tensor([1, 2, 2])


In [125]:
#33
x= torch.tensor([1,0,1,1,1],dtype=torch.bool)
print('x: ',x)
z= torch.any(x) #OR function
print('any: ',z)

z= torch.all(x) #AND function
print('all: ',z)

x= torch.arange(10)
print('x: ',x)
print('Filtering operation: ',torch.where(x>5,x,x**2)) #----IMPORTANT (if x>5 then x otherwise x^2)
print('Unique values: ',torch.tensor([0,0,1,2,2,3,4]).unique())
print('No of dimensions: ',x.ndimension())
print('No of elements in x: ',x.numel()) #similar to len(x) but bit different in case of nD tensor

#difference between numel() and len()--> len() is basically calculates width/row
x1= torch.rand([3,5])
print('No of elements in x1: ',x1.numel(),len(x1))

x:  tensor([ True, False,  True,  True,  True])
any:  tensor(True)
all:  tensor(False)
x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Filtering operation:  tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])
Unique values:  tensor([0, 1, 2, 3, 4])
No of dimensions:  1
No of elements in x:  10
No of elements in x1:  15 3


# Indexing

In [ ]:
#34
# Tensor Indexing
batch_size= 10
features= 25
x= torch.rand((batch_size,features))
print('x: ',x,'shape: ',x.shape,'dtype: ',x.dtype)

print("=====================================================================================================")
print('Features of first example: ')
print('first row and all column in first row: ',x[0],'shape: ',x[0].shape)

print("=====================================================================================================")
print('First feature for all the examples: ')
print(x[:,0],'shape: ',x[:,0].shape)

print("=====================================================================================================")
print('First 10 features of 2nd batch: ')
print(x[2,0:10],'shape: ',x[2,0:10].shape)


x:  tensor([[2.4363e-01, 4.5453e-01, 7.2161e-01, 8.6224e-01, 1.6576e-01, 3.4606e-02,
         6.3573e-01, 8.9671e-01, 7.9575e-02, 8.7158e-01, 4.8972e-01, 7.6993e-01,
         7.6575e-01, 3.6880e-01, 3.8664e-01, 9.7229e-01, 5.1772e-01, 2.0121e-01,
         2.9768e-01, 2.9312e-01, 9.1276e-01, 5.1353e-01, 1.1850e-01, 3.2659e-01,
         3.5205e-03],
        [2.5776e-01, 7.6505e-01, 6.1249e-01, 6.2756e-01, 5.8764e-01, 9.2246e-01,
         5.4764e-03, 4.5845e-01, 6.6566e-01, 7.4318e-01, 2.8549e-01, 7.7764e-01,
         2.8255e-03, 7.0235e-02, 7.4854e-01, 1.2565e-01, 9.8555e-01, 7.7706e-01,
         9.9150e-01, 9.6626e-01, 4.2208e-01, 6.8494e-01, 1.8177e-01, 4.4228e-01,
         2.5131e-01],
        [7.1366e-01, 6.9828e-01, 2.0584e-01, 7.0686e-01, 2.1947e-01, 2.8917e-01,
         6.4427e-01, 9.2741e-02, 7.1429e-01, 8.8802e-02, 4.1933e-01, 9.8537e-01,
         4.3263e-01, 7.4812e-01, 7.0368e-01, 3.5995e-01, 5.2682e-02, 4.8455e-01,
         7.7825e-01, 2.0237e-01, 8.1941e-01, 3.5981e-01, 1.17

In [ ]:
#35
#Fancy Indexing
x= torch.arange(10)
print('x: ',x)
idices= [2,5,8]
print('indexed values: ',x[indices])

print("=====================================")

x= torch.rand((3,5))
print('x: ',x)
rows= torch.tensor([1,0])
cols= torch.tensor([4,0])
print('Indexed value: ',x[rows,cols])

print("=====================================")

x= torch.arange(10)
print('x: ',x)
print('indexed value: ',x[(x<2) | (x>8)])
print('indexed value: ',x[(x>2) & (x<8)])
print('indexed values: ',x[x.remainder(2)==0]) #elementwise x%2==0 will be filtered  -----Important


# Tensor Reshaping

[Difference between reshape and view](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

In [139]:
x= torch.arange(9)
x_3x3= x.view(3,3)
x_reshaped= x.reshape(3,3)
print('x: ',x)
print('x_3x3: ',x_3x3)
print('x_reshaped: ',x_reshaped)

print("====================================Experiment=======================================")
a= torch.arange(9)
print('a: ',a)
print("-------------------->")
b= a.view(3,3)
print('b: ',b)
print("-------------------->")
c= b.t()
print('c: ',c)
print("-------------------->")
# d= c.view(9) # This will throw error
d= c.contiguous().view(9)
print('d: ',d)
print("====================>")
x= a.reshape(3,3)
print('x: ',x)
print("-------------------->")
y= x.t()
print('y:',y)
print("-------------------->")
z= y.reshape(9)
print('z: ',z)




x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
x_3x3:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
x_reshaped:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
====================================Experiment=======================================
a:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
-------------------->
b:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
-------------------->
c:  tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
-------------------->
d:  tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
====================>
x:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
-------------------->
y: tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
-------------------->
z:  tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
