<a href="https://colab.research.google.com/github/novoforce/Exploring-Pytorch/blob/master/new/1000_Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Video_Link](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=2)

In [1]:
import torch

# Initialising the tensors

In [2]:
#1
my_tensor= torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
#2
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
#3
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cuda')
print(my_tensor)

RuntimeError: ignored

In [5]:
#4
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cpu') #cpu is the default
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
#5
#for calculating the gradients
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [8]:
#6
#CUDA- Compute Unified Device Architecture   https://en.wikipedia.org/wiki/CUDA#:~:text=CUDA%20(Compute%20Unified%20Device%20Architecture,API)%20model%20created%20by%20Nvidia.
#the best way to add device(cpu/gpu) 
device= "cuda" if torch.cuda.is_available() else "cpu"
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device) #cpu is the default
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Other initialization methods

In [16]:
#7
x= torch.empty(size=(3,3)) #x will contain random values without any distribution
print(x)

tensor([[1.9487e-35, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [17]:
#8
x= torch.zeros((3,3)) #since 'size' is the first attribute so need to mention explicitly
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
#9
#random values from uniform distribution from 0 to 1
x= torch.rand((3,3))
print(x)

tensor([[0.3693, 0.8113, 0.6868],
        [0.9864, 0.9973, 0.5957],
        [0.9985, 0.1162, 0.0259]])


In [19]:
#10
x= torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
#11
#This will create a Identity matrix
x= torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [22]:
#12
x= torch.arange(start=0,end=5,step=1) #same like range() in python
print(x)

tensor([0, 1, 2, 3, 4])


In [24]:
#13
x= torch.linspace(start=0.1,end=1,steps=10) #start at 0.1 and end at 1 and will have exactly 10 values
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [30]:
#14
x= torch.empty((1,5)).normal_(mean=0,std=1) #empty values will be normally distributed
print(x)
print("==============================================================")
x= torch.empty((1,5))
print('unitialized tensor---->',x)
x.normal_(mean=0,std=1)
print('unitialized tensor after normalizing---->',x)

tensor([[-2.2369, -0.3737, -0.1161, -0.8447,  0.3866]])
unitialized tensor----> tensor([[1.8931e-35, 0.0000e+00, 1.5353e+00, 7.0234e-02, 1.1293e-02]])
unitialized tensor after normalizing----> tensor([[ 0.3507,  0.9553, -0.4190,  0.7268, -0.9332]])


In [33]:
#15
x= torch.empty((1,5)).uniform_(0,1) #here 0,1 is the lower and the upper range
print(x)

tensor([[0.5713, 0.6838, 0.2560, 0.1015, 0.6552]])


In [35]:
#16
x= torch.diag(torch.ones(3)) #3x3 diagona matrix 
print(x)

#similar to code snippet #11
#Note: torch.diag is used to preserve the diagonal values whereas the torch.eye() is used for diagonal= 1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# Attributes of tensors

In [14]:
#7
my_tensor= torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad) #this will be true if the my_tensor has gradient

torch.float32
cpu
torch.Size([2, 3])
True


# How to initialize and convert tensors to other types(int,float,double)

In [43]:
#17
tensor= torch.arange(4)
print(tensor,'datatype->',tensor.dtype)
print(tensor.bool(),'datatype->',tensor.bool().dtype)
print(tensor.short(),'datatype->',tensor.short().dtype)
print(tensor.long(),'datatype->',tensor.long().dtype)# IMPORTANT
print(tensor.half(),'datatype->',tensor.half().dtype)
print(tensor.float(),'datatype->',tensor.float().dtype)# IMPORTANT

tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([False,  True,  True,  True]) datatype-> torch.bool
tensor([0, 1, 2, 3], dtype=torch.int16) datatype-> torch.int16
tensor([0, 1, 2, 3]) datatype-> torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16) datatype-> torch.float16
tensor([0., 1., 2., 3.]) datatype-> torch.float32


# Array to Tensor conversion and vice-versa

In [ ]:
#18
import numpy as np

In [44]:
#19
np_array= np.zeros((5,5))
print('np_array:',np_array)
tensor= torch.from_numpy(np_array)
print('tensor:',tensor)
np_array_back= tensor.numpy()
print('np_array_back:',np_array_back)

np_array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
np_array_back: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math & Comparison Operations

In [45]:
#20
x= torch.tensor([1,2,3])
y= torch.tensor([9,8,7])

In [55]:
#21
#Addition operations
z1= torch.empty(3)
torch.add(x,y,out=z1) #first way
print('Addition: ',z1)
print("============================")
z2= torch.add(x,y) #second way
print('Addition: ',z2)
print("============================")
z3= x+y #third way
print('Addition: ',z3)

#Subtraction operation
z= x-y
print('Subtarction: ',z)

Addition:  tensor([3., 4., 5.])
Addition:  tensor([3, 4, 5])
Addition:  tensor([3, 4, 5])
Subtarction:  tensor([-1,  0,  1])


In [57]:
#22
#Division operation
z= torch.true_divide(x,y) #will do element wise division and return the values in the form of tensor
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2])
z= torch.true_divide(x,y) # this will divide x/y elementwise
print('Division: ',z)

x= torch.tensor([1,2,3])
y= torch.tensor([2,3])
z= torch.true_divide(x,y) #This will throw error as len(x) !=len(y)
print('Division: ',z)

RuntimeError: ignored